//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLSachEntities : DbContext
    {
        public QLSachEntities()
            : base("name=QLSachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHopDong> ChiTietHopDongs { get; set; }
        public virtual DbSet<CTDH_KH> CTDH_KH { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<DonHang_KH> DonHang_KH { get; set; }
        public virtual DbSet<DonHang_NCC> DonHang_NCC { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhaNangCungCap> KhaNangCungCaps { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
    
        public virtual int ThemDonHang(Nullable<int> masach, Nullable<System.DateTime> ngaygiao, Nullable<int> soluong, string tinhtrang, Nullable<int> mahopdong)
        {
            var masachParameter = masach.HasValue ?
                new ObjectParameter("masach", masach) :
                new ObjectParameter("masach", typeof(int));
    
            var ngaygiaoParameter = ngaygiao.HasValue ?
                new ObjectParameter("ngaygiao", ngaygiao) :
                new ObjectParameter("ngaygiao", typeof(System.DateTime));
    
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var tinhtrangParameter = tinhtrang != null ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(string));
    
            var mahopdongParameter = mahopdong.HasValue ?
                new ObjectParameter("mahopdong", mahopdong) :
                new ObjectParameter("mahopdong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThemDonHang", masachParameter, ngaygiaoParameter, soluongParameter, tinhtrangParameter, mahopdongParameter);
        }
    
        public virtual ObjectResult<ThongTinSanPham_Result> ThongTinSanPham(Nullable<int> mancc)
        {
            var manccParameter = mancc.HasValue ?
                new ObjectParameter("mancc", mancc) :
                new ObjectParameter("mancc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongTinSanPham_Result>("ThongTinSanPham", manccParameter);
        }
    }
}
