//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int ID { get; set; }
        public string Consumer_key { get; set; }
        public string Request_token { get; set; }
        public string Veritify_token { get; set; }
        public string Access_token { get; set; }
        public Nullable<int> MaNCC { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
